In [2]:
import duckdb
import pandas as pd

In [31]:
def create_con():
    con = duckdb.connect(database=':memory:')
    return con

def execute_local(con, query):
    result = con.execute(query).fetchdf()
    return result

con = create_con()
q = '''
        CREATE TABLE patients AS SELECT * FROM read_csv_auto('Data/synthetic/csv/patients.csv')
    '''
execute_local(con, q)
patients = execute_local(con, '''select * from patients limit 10''')
patients

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,b8d8578a-3403-a5c5-6e44-19cae89e66e6,1996-09-18,NaT,999-63-4686,S99918900,X11471625X,Mr.,Josiah310,Marks830,NaN,...,Lelystad Flevoland NL,200 Reynolds Pathway,Lelystad,Flevoland,Lelystad,8241,52.535897,5.506974,0.0,28196.83
1,6f196958-2892-9208-d039-3bc0da53e441,1967-11-10,NaT,999-78-7949,S99918013,X21477417X,Mrs.,Chanel977,Corkery305,NaN,...,Lelystad Flevoland NL,470 Spencer View Suite 70,Emmeloord,Flevoland,Emmeloord,8303,52.721992,5.813659,0.0,401884.43
2,16b4683a-7530-6f59-8b55-55c2ff94cb4a,1981-12-03,NaT,999-66-8820,S99992638,X61515580X,Mr.,Shelton25,Kirlin939,NaN,...,Lelystad Flevoland NL,1057 Von Orchard Unit 94,Urk,Flevoland,Urk,8321,52.635535,5.612077,0.0,54141.90
3,30043951-c45e-bd62-73bf-33416a271dea,1997-07-16,NaT,999-22-6918,S99927851,X19029264X,Ms.,Marcia467,Ryan260,NaN,...,Lelystad Flevoland NL,754 Grady Overpass,Zeewolde,Flevoland,Zeewolde,3897,52.398065,5.459499,0.0,54159.71
4,03b2c661-cd30-40a7-2afd-d600d07533da,1966-01-09,NaT,999-31-6521,S99976066,X81949173X,Mr.,Michel472,Berge125,NaN,...,Emmeloord Flevoland NL,580 Fahey Spur Suite 8,Ens,Flevoland,Ens,8307,52.642471,5.837429,0.0,96259.27
5,2ad99a46-7e66-5303-bc5a-940aad8bafcb,1994-06-13,NaT,999-37-9505,S99995912,X192944X,Ms.,Donald774,Yundt842,NaN,...,Lelystad Flevoland NL,700 Medhurst Crossing,Zeewolde,Flevoland,Zeewolde,3895,52.393815,5.454692,0.0,312474.67
6,086c6e12-fbd2-2d12-7cea-7e1d44cd1f46,1986-07-05,NaT,999-78-4854,S99957666,X40030493X,Mrs.,Roseanne877,Haley279,NaN,...,Lelystad Flevoland NL,594 Crooks Trailer,Biddinghuizen,Flevoland,Biddinghuizen,8256,52.404829,5.698442,0.0,1402020.54
7,7719bfb9-ed61-ec55-b396-3da5ef73fe68,1962-05-23,2009-05-08,999-56-5735,S99913267,X18711744X,Mr.,Broderick767,Bosco882,NaN,...,Dronten Flevoland NL,374 Mills Overpass Suite 10,Emmeloord,Flevoland,Emmeloord,8301,52.707820,5.772400,0.0,90663.50
8,fab21351-6ab6-4450-4736-6244f5f8c81d,2002-10-18,NaT,999-55-1604,S99961425,NaN,Ms.,Richelle340,Champlin946,NaN,...,Lelystad Flevoland NL,881 Lynch Lane Apt 40,Lelystad,Flevoland,Lelystad,8232,52.485841,5.452088,0.0,911126.90
9,33c3ea61-40d8-3f64-76ae-2fbb6fa79558,2005-05-17,NaT,999-80-8567,S99978977,NaN,NaN,Rich940,Hagenes547,NaN,...,Emmeloord Flevoland NL,164 Haley Ranch Suite 63,Zeewolde,Flevoland,Zeewolde,3893,52.369475,5.523317,0.0,26385.76

In [81]:
def distinguishable(x, y):
    if not len(x) == len(y):
        return True
    if x.equals(y):
        return False
    return True

def validate_k_anonimity(df):

    for i in range(len(df)):
        for j in range(len(df)):
            if i == j:
                continue
            current = df.iloc[i]
            
            print(distinguishable(current, current))
            
            return

validate_k_anonimity(patients)

AttributeError: 'str' object has no attribute 'equals'